### PR TITLE
fix: use building blocks in independent processes

### LINKED ISSUE #547: [FE+BE?] Building block process links support in independent processes
Within the context of an independent proces (not under case or building block), doc: is not supported and it must be verified whether filling in pv here works.

Also, it says Dossier/Case on the left hand side of the input mapping and the right hand side of the output mapping, but it should say 'Process'

### PR DESCRIPTION
**Pull request by mbritense**
closes https://github.com/generiekzaakafhandelcomponent/gzac-issues/issues/547

### CODE REVIEW

File: backend/building-block/src/main/kotlin/com/ritense/buildingblock/processlink/service/BuildingBlockCallActivityListener.kt [hunk 1]
```diff
@@ -57,16 +57,28 @@ class BuildingBlockCallActivityListener(
             // Check if we're inside a parent building block (nested building block scenario)
             val parentBuildingBlockInstance = findParentBuildingBlockInstance(execution)
 
+            // Determine if this is an independent process (no case, no parent building block)
+            val isIndependentProcess = parentBuildingBlockInstance == null && execution.businessKey == null
```
Comment (ivo-ritense) [inline backend/building-block/src/main/kotlin/com/ritense/buildingblock/processlink/service/BuildingBlockCallActivityListener.kt]: Not sure if the business key is always null for independent processes

**Review by ivo-ritense — APPROVED** [review]

**Review by teodor-ritense — APPROVED** [review]
