### PR TITLE
fix: don't load data for custom widgets

### LINKED ISSUE #568: Widget data fetch request is initiated for a Custom case widget
## Affected version
v13

## Expected behavior
Widget data fetching for custom case widgets on a tab should not happen as the custom case widget itself is responsible for this.

## Current behavior
A widget data request for each custom case widget on a tab is triggered. These request always result in a 404.

Image

## Possible solution (optional)
As it is know it concerns a custom widget, these could be excluded from the widget data fetching logic.

## Steps to reproduce
*Provide an unambiguous set of steps to reproduce this bug.*
*Include code to reproduce, if relevant*
1. Configure a tab with one or more custom case widgets
2. Open the Case detail page and the specific tab containing the custom widget(s)
3. Check the debug log and look for 404 errors to resource formatted like: `/api/v1/document/[document-uuid]/widget-tab/[tab-key]/widget/[widget-key]`

### PR DESCRIPTION
**Pull request by mbritense**
Also adds test custom widget.
Closes https://github.com/generiekzaakafhandelcomponent/gzac-issues/issues/568

### CODE REVIEW

File: frontend/src/app/clock-widget/clock-widget.component.ts [hunk 1]
```diff
@@ -0,0 +1,87 @@
+/*
+ * Copyright 2015-2025 Ritense BV, the Netherlands.
```
Comment (sofiaIvarsRitense) [inline frontend/src/app/clock-widget/clock-widget.component.ts]: 2026

File: frontend/src/app/clock-widget/clock-widget.component.ts [hunk 2]
```diff
@@ -0,0 +1,87 @@
...
+  selector: 'app-clock-widget',
+  standalone: true,
+  imports: [CommonModule],
+  template: `
+    <div class="clock-widget">
+      <p class="clock-widget__subtitle">{{ subtitle }}</p>
+      <p class="clock-widget__time">{{ time() }}</p>
+    </div>
+  `,
+  styles: [
```
Comment (sofiaIvarsRitense) [inline frontend/src/app/clock-widget/clock-widget.component.ts]: Why is this not included in scss file?

File: frontend/src/app/clock-widget/clock-widget.component.ts [hunk 3]
```diff
@@ -0,0 +1,87 @@
...
+
+import {ChangeDetectionStrategy, Component, Input, OnDestroy, OnInit, signal} from '@angular/core';
+import {CommonModule} from '@angular/common';
+import {CustomWidget} from '@valtimo/layout';
+
+@Component({
+  selector: 'app-clock-widget',
+  standalone: true,
+  imports: [CommonModule],
+  template: `
```
Comment (sofiaIvarsRitense) [inline frontend/src/app/clock-widget/clock-widget.component.ts]: Why is this not included in html file?

**Review by marijnritense — APPROVED** [review]

**Review by sofiaIvarsRitense — APPROVED** [review]
